import { ScrollView, View, Text, Pressable, StyleSheet } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useRouter } from "expo-router";
import { colors, spacing, radius } from "@/theme/colors";

export default function TosScreen() {
  const router = useRouter();

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <Pressable onPress={() => router.back()} hitSlop={8}>
          <Text style={styles.back}>← Back</Text>
        </Pressable>
      </View>

      <ScrollView contentContainerStyle={styles.scrollContent}>
        <Text style={styles.title}>Terms & Privacy</Text>
        <Text style={styles.updated}>Last updated: June 24, 2026</Text>

        <Text style={styles.sectionTitle}>Aurae is an AI, not a person</Text>
        <Text style={styles.body}>
          Aurae's companions (Chloe, Maya, Ethan, Jayden, and others) are AI characters generated by a
          language model. They are not real people and do not have thoughts, feelings, or memories
          outside of what this app stores and provides to them. Nothing a companion says is professional
          advice — medical, legal, financial, or otherwise. The service is provided "AS IS" and "AS
          AVAILABLE." We do not guarantee the accuracy, safety, or appropriateness of any AI-generated
          content, and we disclaim all liability for actions taken based on companion responses.
        </Text>

        <Text style={styles.sectionTitle}>Limitation of liability</Text>
        <Text style={styles.body}>
          To the maximum extent permitted by law, Aurae's total liability for any claim arising from your
          use of the app will not exceed the greater of (a) the amount you paid us in the 12 months
          before the claim arose, or (b) $100 USD. We are not liable for indirect, incidental, special,
          or consequential damages, even if we've been advised they were possible.
        </Text>

        <Text style={styles.sectionTitle}>Who can use Aurae</Text>
        <Text style={styles.body}>
          Aurae is intended for adults 18 years of age or older. By using Aurae, you confirm that you
          meet this age requirement. We do not knowingly allow anyone under 18 to create an account.
        </Text>

        <Text style={styles.sectionTitle}>Your data</Text>
        <Text style={styles.body}>
          We store the name you provide, your chat messages, and an optional profile photo, in order to
          run the app and let your companion remember past conversations. We do not sell your personal
          data to third parties, nor do we share it for cross-context behavioral advertising. Chat
          messages may be processed by our AI providers strictly as a business purpose to generate
          replies. You can request deletion of your account and data at any time by contacting us below.
        </Text>

        <Text style={styles.sectionTitle}>Safety & crisis support</Text>
        <Text style={styles.body}>
          Aurae screens conversations for signs of self-harm or suicidal thoughts. If this happens, your
          companion will respond with care and point you toward professional resources, including the 988
          Suicide & Crisis Lifeline (call or text 988 in the US). Aurae is not a substitute for
          professional mental health care, and companions are not equipped to handle emergencies. If you
          are in immediate danger, please contact local emergency services.
        </Text>

        <Text style={styles.sectionTitle}>Subscriptions</Text>
        <Text style={styles.body}>
          Aurae offers a free tier with a daily message limit, and an optional Aurae Premium
          subscription with substantially higher limits. Subscriptions renew automatically until
          cancelled and are billed through your app store account. All purchases are final and
          non-refundable, subject to the respective app store platform's terms.
        </Text>

        <Text style={styles.sectionTitle}>Acceptable use</Text>
        <Text style={styles.body}>
          Don't use Aurae to harass others, generate illegal content, or attempt to bypass age or safety
          protections. We may suspend or terminate accounts that violate these terms.
        </Text>

        <Text style={styles.sectionTitle}>Governing law & dispute resolution</Text>
        <Text style={styles.body}>
          These terms are governed by the laws of the State of Delaware, USA, without regard to its
          conflict-of-laws principles. Choosing Delaware law for this contract does not exempt us from
          disclosure, safety, or other obligations imposed by the state where you are located — those
          requirements apply based on where you use the app, not based on this clause.{"\n\n"}
          Any dispute arising from these terms or your use of Aurae will be resolved through binding,
          individual arbitration administered by the American Arbitration Association (AAA) under its
          Consumer Arbitration Rules, rather than in court — except that either party may bring an
          individual claim in small claims court if it qualifies. You and Aurae each waive any right to a
          jury trial or to participate in a class, collective, or representative action. You may opt out
          of this arbitration agreement within 30 days of first accepting these terms by emailing
          [support email] with your name and a clear statement that you wish to opt out.
        </Text>

        <Text style={styles.sectionTitle}>Severability</Text>
        <Text style={styles.body}>
          If any provision of these terms is found unenforceable, the remaining provisions will remain in
          full force and effect.
        </Text>

        <Text style={styles.sectionTitle}>Changes to these terms</Text>
        <Text style={styles.body}>
          We may update these terms as Aurae evolves. Continued use after an update means you accept the
          revised terms.
        </Text>

        <Text style={styles.sectionTitle}>Contact</Text>
        <Text style={styles.body}>Questions, data deletion requests, or feedback: [support email]</Text>

        <Text style={styles.footerNote}>
          This is a general template and has not been reviewed by a lawyer. Review with legal counsel
          before relying on it — especially the arbitration section, given evolving state laws (Oregon,
          Washington) that grant users a direct right to sue.
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xs,
  },
  back: {
    fontSize: 13,
    color: colors.textTertiary,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xl,
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    color: colors.textPrimary,
    marginTop: spacing.sm,
  },
  updated: {
    fontSize: 12,
    color: colors.textTertiary,
    marginTop: spacing.xs,
    marginBottom: spacing.lg,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.textPrimary,
    marginTop: spacing.lg,
    marginBottom: spacing.xs,
  },
  body: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 21,
  },
  footerNote: {
    fontSize: 11,
    color: colors.textTertiary,
    fontStyle: "italic",
    marginTop: spacing.xl,
    lineHeight: 16,
  },
});
